config/routes.rb
Reservester::Application.routes.draw do
  get "reservations/create"
  get "reservations/destroy"
  devise_for :owners
  get "users/new"
  get "welcome/index"

  resources :restaurants do
    resources :reservations
  end 
  root to: "restaurants#index"
  match '/signup',  to: 'owners#new',            via: 'get'

  

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  
#  validates :name, :email, presence: true
  
  has_many :restaurants, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  validates :email, presence: true
  validates :requested_date, presence: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  attr_accessible :name, :description, :address1, :address2,
                    :city, :state, :zip, :phone, :image, :menu
	validates :name, presence: true,
	            length: { minimum: 3 }, uniqueness: { case_sensitive: false }
  validates :phone, presence: true
#<%= f.hidden_field :menu_cache %> in form partial doesn't work currently because of this validation
  validates :image, presence: true

  
  mount_uploader :image, ImageUploader
  mount_uploader :menu, MenuUploader
  
  belongs_to :owner 
  has_many :reservations, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    before_filter :authenticate_owner!, except: [:index]

    def index
      @owners = Owner.all
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.build(reservation_params)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.find_by(id: params[:id])
    if @reservation.destroy
      redirect_to @restaurant, notice: 'Reservation successfully deleted'
    else
      redirect_to @restaurant, notice: 'There was an error deleting the reservation'
    end
  end
  
  def show
  end
  
  def index
  end
  
  def new
  end
  
  def edit
  end
  
  def update
  end
  
  private

  def reservation_params
    params.require(:reservation).permit(:email, :requested_date)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_filter :authenticate_owner!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :confirm_ownership, only: [:edit, :update, :destroy]
	
	def new
	  @restaurant=Restaurant.new
    @owner=current_owner
	end

	def create
		@restaurant = current_owner.restaurants.build(restaurant_params)
		@owner=current_owner

		if @restaurant.save
			redirect_to @restaurant, notice: "#{@restaurant.name} was successfully created!"
		else
			render :new
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@owner=current_owner
	end

	def index
		@restaurants = Restaurant.all
	
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@owner=current_owner

    if @restaurant.update_attributes(params[:restaurant])
     redirect_to @restaurant, notice: "#{@restaurant.name} was successfully updated."
		else
			render :edit		
		end
	end

	def destroy
	  @owner=current_owner
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy

		redirect_to restaurants_path, alert: "#{@restaurant.name} was successfully deleted!"
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :description, :address1, :address2, :city, :state, :zip, :phone, :image, :menu, :owner_id)
	end		


  def confirm_ownership
   @restaurant = Restaurant.find(params[:id])
   if @restaurant.owner != current_owner
     redirect_to @restaurant, notice: "You don't own #{@restaurant.name}!"
   end
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_owner!, except: [:index]
  def new
    @user = User.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
    def full_title(page_title)
      base_title = "Reservester"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	<a>
	 <%= link_to image_tag("R.png", alt: "R")+"eservester",'#', id: "logo" %>
    </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
	  <%= link_to image_tag("Rbig.png", alt: "R")+"eservester",restaurants_path, id: "logo" %>

       <nav>
	    <ul class="nav pull-right">
	      <li>
	          <% if owner_signed_in? %>
	            <%= link_to "Sign Out", destroy_owner_session_path, method: :delete, class: "float-right" %>
	          <% else %>
	            <%= link_to "Sign In", new_owner_session_path, class: "float-right" %>
	          <% end %>
	      </li>
	    </ul>
      </nav>

    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 </head>
 <body>
  
  <div class = "container-fluid">
	<%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
           <button type = "button" class = "close" data-dismiss = "<%= key %>">&times;</button>
            <%= value %>
      </div>
    <% end %>
	
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

 </body>
 <div class="span6">
       </br>
		
       </br>
	   <%= debug(params) if Rails.env.development? %>
       
 </div>
</html>

app/views/owners/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@owner) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :class => 'form-horizontal' }, data: {validate: 'parsley'}, novalidate: 'novalidate' do |f| %>

<% if @restaurant.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:
    </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<fieldset>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', placeholder: 'Name', :"data-required" => "true", :"data-notblank" => "true", autofocus: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field', placeholder: 'Description' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address1, :class => 'text_field', placeholder: 'Number and Street' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address2, :class => 'text_field', placeholder: 'Apartment Number' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field', placeholder: 'City' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field', placeholder: 'State' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zip, :class => 'text_field', placeholder: 'Zip', :"data-type" => "digits" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field', placeholder: 'Phone', :"data-required" => "true", :"data-notblank" => "true", :"data-type" => "phone" %>
    </div>
  </div>

  <div class="control-group">
	<%= f.label :image, :class => 'control-label' %>
	
    
    <div class="controls">

	  <%= f.file_field :image %></br>
    </div>
   
    <div class="controls">
	 <%= f.label :remote_image_url, "or image URL" %>
	
     <%= f.text_field :remote_image_url, :class => 'text_field', placeholder: 'Image URL' %>
     <%= f.hidden_field :image_cache, :value => @restaurant.image_cache %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :menu, :class => 'control-label' %>

    <div class="controls">
	  <%= f.file_field :menu %></br>
    </div>

    <div class="controls">
	  <%= f.label :remote_menu_url, "or image URL" %>
      <%= f.text_field :remote_menu_url, :class => 'text_field', placeholder: 'Menu URL' %>
      <%= f.hidden_field :menu_cache, :value => @restaurant.menu_cache %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurants_path, :class => 'btn' %>
  </div>
</fieldset>
<% end %>

app/views/restaurants/_reservation_form.html.erb
<div class = "span2">
<h1><%= @restaurant.name %></h1>
</div>

app/views/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>

<div class="page-header">
  <% if false %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <% end %>
  <h1><%=t '.title', :default => 'The restaurants you wish existed.' %></h1>
  <h2><%=t '.title', :default => 'Choose a restaurant. Make your reservation. Nevermind reality.' %></h2>
</div>




<div class="container-fluid">
	
	<div class="row">

          <% @restaurants.each do |restaurant| %>
		    <div class="restaurant-wrap">	   			
		       <div class="col-lg-4 col-md-1 col-xs-6 thumb">
			
		         <div class="thumbnail-test">
		           <%= link_to (image_tag restaurant.image_url(:thumb).to_s), restaurant_path(restaurant) %>		    
		           <div class="caption-description">
			         <br><em><%= restaurant.description %></em></br>
                   </div>
			     </div>
               
			     <div class="thumbnail">
				   <div class="caption">
		             <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>		        
			         <%= restaurant.address1 %> <%= restaurant.address2 %>
		             <p><%= restaurant.city %>, <%= restaurant.state %> <%= restaurant.zip %></p>
		             <p><b>Proprietor:</b> <%= restaurant.owner.name %></p>
		           </div>		    		    	 	    
		         </div>
		      </div>
            </div>
          <% end %>

    </div>
</div>

	    
	    <% if false %>
	    <%= restaurant.owner(:name) %></br>      
        <div>
	      <% if owner_signed_in? && restaurant.owner == current_owner %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurant_path(restaurant), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurant_path(restaurant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </div>
        <% end %>



<% if owner_signed_in? %>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurant_path,
            :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="container-fluid">
	

	
	<div class="row">
	   <div class="restaurant-wrap">
		  <div class="col-lg-4 col-md-2 col-xs-6 thumb">
			<div class="thumbnail">
				<div class="info-text">
	               <h1><%=t '.title', :default => model_class.human_attribute_name(@restaurant.name).titleize %></h1>
	              
	            </div>
		      </div>
           </div>
	   </div>
          
		    <div class="restaurant-wrap-show">	   			
		       <div class="col-lg-2 col-md-1 col-xs-6 thumb">
				<div class="thumbnail">
				   <div class="title-caption">
		             <h4><em><%= @restaurant.description %></em></h4>
			       </div>
                </div>
		        <%= image_tag @restaurant.image_url(:masthead).to_s %>		    

			  
               
			     <div class="thumbnail">
				   <div class="caption">
		             <h3><%= @restaurant.name %></h3>		        
			         <%= @restaurant.address1 %> <%= @restaurant.address2 %>
		             <p><%= @restaurant.city %>, <%= @restaurant.state %> <%= @restaurant.zip %></p>
		             <p><b>Proprietor:</b> <%= @restaurant.owner.name %></p>
		           </div>		    		    	 	    
		         </div>
		      </div>
            </div>
    </div>



</div>




<div class="form-actions">
              <%= link_to t('.back', :default => t("helpers.links.back")), restaurants_path, :class => 'btn'  %>

			  <% if owner_signed_in? && @restaurant.owner == current_owner %>
			    <%= link_to t('.edit', :default => t("helpers.links.edit")),
			              edit_restaurant_path(@restaurant), :class => 'btn' %>
			    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			              restaurant_path(@restaurant),
			              :method => 'delete',
			              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			              :class => 'btn btn-danger' %>
			 <% end %>

</div>


  <% if owner_signed_in? && @restaurant.owner == current_owner %>
  <% else %>
    <div class="form-actions">
      <h5>Make a reservation!</h5>
      <%= render 'reservation_form' %>
    </div>
  <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Hello, Reservester!</h1>
<%= link_to "My Restaurants", controller: "restaurants" %>